import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { StoreInitializer } from "@/components/StoreInitializer";
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import SideNav from "@/components/SideNav";
import MainLayout from "@/components/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
    >
      <html lang="en">
        <body className={GeistSans.className}>
          <StoreInitializer />
          <div className="flex min-h-screen">
            <SideNav />
            <MainLayout>
              {children}
            </MainLayout>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
