import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { StoreInitializer } from "@/components/StoreInitializer";
import { ClerkProvider } from '@clerk/nextjs'
import SideNav from "@/components/SideNav";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={GeistSans.className}>
          <StoreInitializer />
          <SideNav />
          <div className="ml-64 flex flex-col min-h-screen">
            <Header />
            <main className="flex-1 overflow-y-auto p-6">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
